site_name: Boats Animator
site_dir: bin/mkdocs
repo_url: https://github.com/charlielee/boats-animator
pages:
- Home: index.md
- Introduction:
  - "About Boats Animator": introduction/about.md
  - "System requirements": introduction/system-requirements.md
  - License: introduction/license.md
- "Getting started":
  - Setup: getting-started/setup.md
- "Features":
  - "Export video": features/export-video.md
  - "Keyboard shortcuts": features/keyboard-shortcuts.md
  - "Launcher window": features/launcher-window.md
  - "Main window": features/main-window.md
theme: readthedocs
extra_css: [css/custom.css]
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.tables
  - markdown.extensions.toc
